### ISSUE TITLE
Capping the river corridor

### ISSUE THREAD

**Issue by fnattino** [CityRiverSpaces/prototyping#22]
We have different options for "capping" the river corridor:

* Using a pre-defined polygon, like the city boundary (currently implemented).
* Directly connecting the nodes used as end-points of the two corridor edges.
* Using a shortest-path approach, in a way that is similar to how the corridor edges are found (see @cforgaci's [review comment](https://github.com/CityRiverSpaces/prototyping/pull/20#issuecomment-2409097577) in #20 ): 

> Following the morphological approach to delineation, it makes more sense to follow the same approach when capping too. I suggest we cap by default with a shortest path between the valley edge end points rather than using the admin boundary.

**Comment by fnattino** [comment]
The first option (the city boundary one) is actually the less relevant, as it can be obtained from one of the others by simple intersections, so I believe we can actually skip it (or maybe offer it as a post-processing step).

**Comment by cforgaci** [comment]
@fnattino we can close this issue, right?

**Comment by fnattino** [comment]
Yes @cforgaci - "closing" apparently does not connect issue to PRs ([only "close"/"closes"/"closed" work](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue)). Thanks!
