### ISSUE TITLE
River valley delineation

### ISSUE THREAD

**Issue by fnattino** [CityRiverSpaces/prototyping#6]
We would like to identify a robust approach to determine valley edge boundary from a digital terrain model (issue based on #1). 

Potential approaches identified until now: 

* ArcGIS-based method from the Vermont Agency of Natural Resources.
* Method based on [`r.geomorphon`](https://grass.osgeo.org/grass84/manuals/r.geomorphon.html) from rgrass (based on GRASS GIS) - also see #1 
* Rudimentary approach based on thresholding a computed cost-distance function computed on the DTM as quickly implemented in [here](https://github.com/CityRiverSpaces/prototyping/blob/main/notebooks/river-valley/river-valley_bucharest.qmd).

**Comment by cforgaci** [comment]
@rogerkuou this is the paper I mentioned today: 

https://scholarworks.umass.edu/server/api/core/bitstreams/a5fc260a-cb4c-49c6-b83e-029c1b250129/content

The active river area is closest to what we've been looking for.

This is another paper that might be useful:

https://hess.copernicus.org/preprints/hess-2020-361/
