### ISSUE TITLE
Improve network

### ISSUE THREAD

**Issue by fnattino** [CityRiverSpaces/prototyping#7]
In order to use the OSM street network for the application of delineating river corridors, we need to add/improve on the following features:

- [x]  integrate it with the rail network (a starting point for this is available [here](https://github.com/CityRiverSpaces/prototyping/blob/main/notebooks/corridor/street-rail_network_bucharest.qmd)).
- [x] improve on the data cleaning. Right now we are following steps described in the `sfnetwork` [vignette](https://luukvdmeer.github.io/sfnetworks/articles/sfn02_preprocess_clean.html), but we are still limited in that a node cannot be added to crossing edges if a common point is not present in both edge geometries.
- [x] Nice to have: roundabout simplification. This can be otherwise carry out when performing segment delineation with `momepy` (see [notebook](https://github.com/CityRiverSpaces/prototyping/blob/main/notebooks/segments/segments_bucharest.ipynb)).

**Comment by meiertgrootes** [comment]
PR #18 provides the abiity to add nodes at crossing edges.

**Comment by fnattino** [comment]
#19 builds on top of #18 to implement the method for OSM data, #20 applies the roundabout simplification as implemented in momepy.
